name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    if: contains(github.event.commits[0].message, '[skip ci]') == false &&
        github.repository == 'roblox-ts/types' &&
        github.ref == 'refs/heads/deploy'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Install NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 11.x
          registry-url: 'https://registry.npmjs.org'

      - name: Deploy
        run: |
          git config user.name "GitHub Actions"
          git config user.email "noreply@github.com"
          npm version patch -m "package.json version bump to %s [ci skip]"
          git push https://osyrisrblx:${{ secrets.github_token }}@github.com/roblox-ts/types.git HEAD:deploy
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
